# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: maven
    directory: /
    target-branch: development  # TODO: Remove this line if the project doesn't not use a development branch
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    target-branch: development  # TODO: Remove this line if the project doesn't not use a development branch
    schedule:
      interval: monthly
